### ISSUE TITLE
uol_bl_morse

### ISSUE THREAD

**Issue by pet1330** [strands-project/strands_morse#136]
I tried to install the Strands system following [these instructions](https://github.com/strands-project/lamor15/wiki/Individual-Computer-Setup) for the LAMoR Summer School, but was unable to run the morse launch file. I'm not sure if it's a strands_morse error, or a blender error. Does anyone know why this error is occurring?
##### Console Output:

```
peter@localhost:~$ roslaunch strands_morse uol_bl_morse.launch env:=uol_bl_fast
... logging to /home/peter/.ros/log/7457a222-4ca5-11e5-a772-c48e8ff4592f/roslaunch-localhost-9023.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://10.50.12.43:45448/

SUMMARY
========

PARAMETERS
 * /robot/joint_state_publisher/source_list: ['/ptu/state']
 * /robot/robot_description: <?xml version="1....
 * /robot_description: <?xml version="1....
 * /rosdistro: indigo
 * /rosversion: 1.11.13

NODES
  /
    human_pose_simulator (strands_morse/human_pose_simulator.py)
    odometry_republisher (topic_republisher/republish_odometry.py)
    ptu_action_server (scitos_ptu/flir_ptu_action_server.py)
    ptu_jointstate_republisher (topic_republisher/republish_ptu_jointstate.py)
    ptu_state_republisher (topic_republisher/republish_ptu_state.py)
    robot_pose_publisher (robot_pose_publisher/robot_pose_publisher)
    scitos_node (strands_morse/scitos_node.py)
    strands_morse (strands_morse/simulator.sh)
  /robot/
    joint_state_publisher (joint_state_publisher/joint_state_publisher)
    robot_state_publisher (robot_state_publisher/state_publisher)

auto-starting new master
process[master]: started with pid [9041]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 7457a222-4ca5-11e5-a772-c48e8ff4592f
process[rosout-1]: started with pid [9054]
started core service [/rosout]
process[robot/joint_state_publisher-2]: started with pid [9071]
process[robot/robot_state_publisher-3]: started with pid [9072]
process[robot_pose_publisher-4]: started with pid [9097]
process[scitos_node-5]: started with pid [9125]
process[ptu_jointstate_republisher-6]: started with pid [9126]
process[ptu_state_republisher-7]: started with pid [9129]
process[odometry_republisher-8]: started with pid [9135]
process[ptu_action_server-9]: started with pid [9164]
/opt/ros/indigo/lib/topic_republisher/republish_ptu_jointstate.py:12: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.pub = rospy.Publisher('/ptu', Vector3)
process[strands_morse-10]: started with pid [9188]
[INFO] [WallTime: 1440670922.208706] /ptu_jointstate_republisher setting up
process[human_pose_simulator-11]: started with pid [9195]
/opt/ros/indigo/lib/topic_republisher/republish_ptu_state.py:11: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.pub = rospy.Publisher('/ptu/state', JointState)
[INFO] [WallTime: 1440670922.293968] /ptu_state_republisher setting up
Running morse on /opt/ros/indigo/share/strands_morse/uol with PYTHONPATH=/opt/ros/indigo/share/strands_morse/uol/src:/opt/ros/indigo/share/strands_morse/strands_sim/src:/opt/ros/indigo/lib/python2.7/dist-packages and MORSE_RESOURCE_PATH=/opt/ros/indigo/share/strands_morse:/opt/ros/indigo/share/strands_morse/strands_sim/data:/opt/ros/indigo/share/strands_morse/strands_sim/robots:/opt/ros/indigo/share/strands_morse/uol/data:
/opt/ros/indigo/lib/topic_republisher/republish_odometry.py:11: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.pub = rospy.Publisher('/odom', Odometry)
[INFO] [WallTime: 1440670922.381473] /odometry_republisher setting up
[INFO] [WallTime: 1440670922.420683] Starting fake scitos_node
/opt/ros/indigo/lib/strands_morse/scitos_node.py:43: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  pub = rospy.Publisher('motor_status', MotorStatus)
* Using environment <uol>.

* Adding </opt/ros/indigo/share/strands_morse/uol> to PYTHONPATH and MORSE_RESOURCE_PATH.

* Loading simulation </opt/ros/indigo/share/strands_morse/uol/uol_bl_fast.py>.

* morse 1.3.STRANDS.0

/opt/ros/indigo/lib/scitos_ptu/flir_ptu_action_server.py:33: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.ptu_pub = rospy.Publisher('cmd', JointState)
/opt/ros/indigo/lib/strands_morse/human_pose_simulator.py:37: SyntaxWarning: The publisher should be created with an explicit keyword argument 'queue_size'. Please see http://wiki.ros.org/rospy/Overview/Publishers%20and%20Subscribers for more information.
  self.pub = rospy.Publisher(self.out_topic, PoseStamped)
Color management: using fallback mode for management
read blend: /opt/strands-morse-simulator/share/morse/data/morse_default_autorun.blend
Color management: image colorspace "Raw" not found, will use default instead.
strands_sim.robots.scitosA5.Scitosa5: no interfaces available for this component! Check builder/data.py.
`place_camera` is deprecated, use `set_camera_location` instead
`aim_camera` is deprecated, use `set_camera_rocation` instead
Detected GL_ARB_texture_env_combine
Detected GL_ARB_texture_cube_map
Detected GL_ARB_multitexture
Detected GL_ARB_shader_objects
Detected GL_ARB_vertex_shader
Detected GL_ARB_fragment_shader
Detected GL_ARB_vertex_program
Detected GL_ARB_depth_texture
Detected GL_EXT_separate_specular_color
Ignoring Xlib error: error code 171 request code 155
Disabling SWAP INTERVALS extension

Blender Game Engine Started
==============================
Welcome to the MORSE simulator
==============================
PRE-INITIALIZATION
[    0.007] Python Version: 3.4.0
[    0.007] Blender Version: 2.69.0
[    0.007] Python path: ['/opt/strands-morse-simulator/share/morse/data', '/opt/strands-morse-simulator/share/morse/data/props', '/opt/ros/indigo/share/strands_morse/uol/data', '/opt/strands-morse-simulator/share/morse/data/actuators', '/opt/ros/indigo/share/strands_morse/strands_sim/robots', '/usr/share/blender/scripts/addons', '/usr/share/blender/scripts/startup', '/usr/share/blender/scripts/modules', '/opt/ros/indigo/share/strands_morse/uol/src', '/opt/strands-morse-simulator/bin', '/opt/ros/indigo/share/strands_morse/strands_sim/src', '/opt/ros/indigo/lib/python2.7/dist-packages', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/usr/lib/python3.4/lib-dynload', '/usr/local/lib/python3.4/dist-packages', '/usr/lib/python3/dist-packages', '/opt/strands-morse-simulator/lib/python3/dist-packages', '/usr/share/blender/scripts/addons/modules', '/home/peter/.config/blender/2.69/scripts/addons/modules', '/opt/strands-morse-simulator/lib/python3/dist-packages/morse/blender', '/opt/strands-morse-simulator/lib/python3/dist-packages/morse/blender/human_interaction']
[    0.007] PID: 9212
[    0.007] [core.morse_time] Morse configured in Best Effort Mode
[    0.009] Added docking_station as a active object
[    0.009] Added docking_station_label as a active object
[    0.009] [robots.scitosA5] robot initialization
[    0.009] [robots.scitosA5] Component initialized
[    0.010] [sensors.laserscanner] robot.scan initialization
[    0.010] [sensors.laserscanner] Sick: Using arc object: 'Arc_180'
[    0.012] [sensors.laserscanner] Component initialized, runs at 10.00 Hz
[    0.012] Component robot.scan (level: raw) added to robot
[    0.012] [sensors.odometry] Component initialized, runs at 60.00 Hz
[    0.012] Component robot.odometry (level: integrated) added to robot
[    0.043] [sensors.battery_state] robot.battery initialization
[    0.043] [sensors.battery_state] Component initialized, runs at 60.00 Hz
[    0.043] Component robot.battery  added to robot
[    0.073] [actuators.ptu] robot.ptu initialization
[    0.074] [actuators.ptu] Using pan base: 'PanBase'
[    0.074] [actuators.ptu] Using tilt base: 'TiltBase'
[    0.074] [actuators.ptu] Component initialized
[    0.074] Component robot.ptu  added to robot
[    0.086] [sensors.ptu_posture] robot.ptu.ptu_pose initialization
[    0.087] [sensors.ptu_posture] Component <robot.ptu.ptu_pose> initialized, runs at 60.00 Hz
[    0.087] Component robot.ptu.ptu_pose  added to robot
[    0.100] [actuators.keyboard] robot.keyboard initialization
[    0.101] [actuators.keyboard] Component initialized
[    0.101] Component robot.keyboard  added to robot
[    0.118] [actuators.v_omega] robot.motion initialization
[    0.118] [actuators.v_omega] Component initialized
[    0.118] Component robot.motion  added to robot
SUPERVISION SERVICES INITIALIZATION
[    0.128] No multi-node scene configuration file found. Multi-node support disabled.
[    0.160] [middleware.socket_request_manager] Socket service manager now listening on port 4000.
[    0.160] [core.services] Successfully initialized the morse.middleware.socket_request_manager.SocketRequestManager request manager.
[    0.160] Adding 'morse.middleware.socket_request_manager.SocketRequestManager' to the middlewares for simulation control
[    0.160] [core.request_manager] Socket service manager: Synchronous service 'activate' for component 'simulation' successfully registered
[    0.160] [core.request_manager] Socket service manager: Synchronous service 'deactivate' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'details' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'get_camarafp_projection_matrix' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'get_object_bbox' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'get_object_global_bbox' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'get_object_pose' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'get_object_type' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'get_scene_objects' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'list_robots' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'quit' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'reset_objects' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'restore_dynamics' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'set_camarafp_far_clip' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'set_camarafp_position' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'set_camarafp_projection_matrix' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'set_camarafp_transform' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'set_log_level' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'set_object_dynamics' for component 'simulation' successfully registered
[    0.161] [core.request_manager] Socket service manager: Synchronous service 'set_object_pose' for component 'simulation' successfully registered
[    0.162] [core.request_manager] Socket service manager: Synchronous service 'set_object_visibility' for component 'simulation' successfully registered
[    0.162] [core.request_manager] Socket service manager: Synchronous service 'suspend_dynamics' for component 'simulation' successfully registered
[    0.162] [core.request_manager] Socket service manager: Synchronous service 'terminate' for component 'simulation' successfully registered
[    0.162] [core.request_manager] Socket service manager: Synchronous service 'transform_to_obj_frame' for component 'simulation' successfully registered
[    0.162] Adding 'morse.middleware.socket_request_manager.SocketRequestManager' to the middlewares for communication control
[    0.162] [core.request_manager] Socket service manager: Synchronous service 'distance_and_view' for component 'communication' successfully registered
[    0.162] Adding 'morse.middleware.socket_request_manager.SocketRequestManager' to the middlewares for time control
[    0.162] [core.request_manager] Socket service manager: Synchronous service 'mode' for component 'time' successfully registered
[    0.162] [core.request_manager] Socket service manager: Synchronous service 'now' for component 'time' successfully registered
[    0.162] [core.request_manager] Socket service manager: Asynchronous service 'sleep' for component 'time' successfully registered
[    0.162] [core.request_manager] Socket service manager: Synchronous service 'statistics' for component 'time' successfully registered
SUPERVISION SERVICES INITIALIZED
SCENE INITIALIZATION
Python script error - object 'Scene_Script_Holder', controller 'Initialize':
[ERROR][MORSE] Uncaught exception, quit Blender.
Traceback (most recent call last):
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/blender/main.py", line 594, in init
    init_ok = init_ok and link_services()
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/blender/main.py", line 439, in link_services
    if not persistantstorage.morse_services.add_request_manager(request_manager):
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/core/services.py", line 38, in add_request_manager
    instance = create_instance(classpath)
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/helpers/loading.py", line 45, in create_instance
    return klass(*args, **kwargs)
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/middleware/ros_request_manager.py", line 208, in __init__
    RequestManager.__init__(self)
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/core/request_manager.py", line 71, in __init__
    if not self.initialization():
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/middleware/ros_request_manager.py", line 219, in initialization
    rospy.init_node('morse', log_level = rospy.DEBUG, disable_signals=True)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 318, in init_node
    raise rospy.exceptions.ROSInitException("init_node interrupted before it could complete")
rospy.exceptions.ROSInitException: init_node interrupted before it could complete
[ERROR][MORSE] Uncaught exception, quit Blender.
Traceback (most recent call last):
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/blender/main.py", line 594, in init
    init_ok = init_ok and link_services()
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/blender/main.py", line 439, in link_services
    if not persistantstorage.morse_services.add_request_manager(request_manager):
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/core/services.py", line 38, in add_request_manager
    instance = create_instance(classpath)
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/helpers/loading.py", line 45, in create_instance
    return klass(*args, **kwargs)
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/middleware/ros_request_manager.py", line 208, in __init__
    RequestManager.__init__(self)
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/core/request_manager.py", line 71, in __init__
    if not self.initialization():
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/middleware/ros_request_manager.py", line 219, in initialization
    rospy.init_node('morse', log_level = rospy.DEBUG, disable_signals=True)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 318, in init_node
    raise rospy.exceptions.ROSInitException("init_node interrupted before it could complete")
rospy.exceptions.ROSInitException: init_node interrupted before it could complete
Traceback (most recent call last):
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/blender/main.py", line 594, in init
    init_ok = init_ok and link_services()
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/blender/main.py", line 439, in link_services
    if not persistantstorage.morse_services.add_request_manager(request_manager):
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/core/services.py", line 38, in add_request_manager
    instance = create_instance(classpath)
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/helpers/loading.py", line 45, in create_instance
    return klass(*args, **kwargs)
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/middleware/ros_request_manager.py", line 208, in __init__
    RequestManager.__init__(self)
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/core/request_manager.py", line 71, in __init__
    if not self.initialization():
  File "/opt/strands-morse-simulator/lib/python3/dist-packages/morse/middleware/ros_request_manager.py", line 219, in initialization
    rospy.init_node('morse', log_level = rospy.DEBUG, disable_signals=True)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/client.py", line 318, in init_node
    raise rospy.exceptions.ROSInitException("init_node interrupted before it could complete")
rospy.exceptions.ROSInitException: init_node interrupted before it could complete
[strands_morse-10] process has died [pid 9188, exit code 255, cmd /opt/ros/indigo/lib/strands_morse/simulator.sh uol uol_bl_fast.py __name:=strands_morse __log:=/home/peter/.ros/log/7457a222-4ca5-11e5-a772-c48e8ff4592f/strands_morse-10.log].
log file: /home/peter/.ros/log/7457a222-4ca5-11e5-a772-c48e8ff4592f/strands_morse-10*.log
```

**Comment by cdondrup** [comment]
This not just related to the uol_bl environment but a general problem with his morse installation. Maybe @cburbridge or @kunzel have an idea?

**Comment by warp1337** [comment]
I do have the same problem

**Comment by cdondrup** [comment]
@pet1330 do you remember what the problem was and how you fixed it?

**Comment by pet1330** [comment]
I can't remember, I'm not entirely sure I did, But I vaguely remember asking @Jailander

**Comment by Jailander** [comment]
I really can't remember solving this :/ @warp1337 have you tried running the full version as in `roslaunch strands_morse uol_bl_morse.launch`, if that doesn't work please post the error you are getting if it does tell us and I'll take a look at the fast version
