### ISSUE TITLE
Video camera crashes morse

### ISSUE THREAD

**Issue by cburbridge** [strands-project/strands_morse#61]
Morse regularly won't start because of a bug related to the video camera. It starts up, but then just after the scene is initialised it crashes: 

```
[SCENE INITIALIZED]
[    2.498] [sensors.camera]    Focal length of the camera is: 35.0
[    2.498] [sensors.camera]    Near clipping distance of the camera is: 0.10000000149011612
[    2.498] [sensors.camera]    Far clipping distance of the camera is: 100.0
[    2.498] [sensors.camera] Camera 'robot.ptu.videocam': Exporting an image of capsize: (640, 480) pixels
Traceback (most recent call last):
  File "/opt/strands/lib/python3.3/site-packages/morse/blender/calling.py", line 47, in component_action
    cmpt_object.action()
  File "/opt/strands/lib/python3.3/site-packages/morse/core/sensor.py", line 79, in action
    function(self)
  File "/opt/strands/lib/python3.3/site-packages/morse/middleware/ros/video_camera.py", line 43, in default
    image.data = bytes(image_local)
TypeError: 'NoneType' object is not iterable
```

This happens most times, but if I keep restarting eventually I get going.

**Comment by hawesie** [comment]
I'm glad you see this too, as I thought it was just an OS X thing.

**Comment by kunzel** [comment]
@cburbridge I never had this problem with the camera. Do you still have problems under indigo? Or can we close this issue?

**Comment by cburbridge** [comment]
Closed as it appears OK using latest version.
