### ISSUE TITLE
python3-netifaces debian dependency missing

### ISSUE THREAD

**Issue by creuther** [strands-project/strands_morse#95]
When bringing up strands_morse (regardless of environment) on Ubuntu 14.04 (or rather Linux Mint 17) it gives the following error whenever it would subscribe to a topic:

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/threading.py", line 920, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.4/threading.py", line 868, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_pubsub.py", line 168, in robust_connect_subscriber
    conn.connect(dest_addr, dest_port, pub_uri, timeout=60.)
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 524, in connect
    if not rosgraph.network.is_local_address(dest_addr):
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 176, in is_local_address
    local_addresses = ['localhost'] + get_local_addresses()
  File "/opt/ros/indigo/lib/python2.7/dist-packages/rosgraph/network.py", line 218, in get_local_addresses
    import netifaces
ImportError: No module named 'netifaces'
```

This was **fixed by installing the python3-netifaces debian package**. Everything looked fine but obviously there was no communication between morse and the ROS stuff (hence the robot didn't move in any nav2d environment even though valid plans and velocities were given). Thanks to @marc-hanheide for figuring it out.

**Comment by marc-hanheide** [comment]
@cburbridge I think this deep needs to be added to the Debian package that you created?
